apiVersion: v1
kind: ServiceAccount

metadata:
  name: mlops-training
  namespace: mlops
---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: mlops-inference
  namespace: mlops
---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: mlflow
  namespace: mlops