apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlops-training
  namespace: mlops
  annotations:
    azure.workload.identity/client-id: TRAINING_IDENTITY_CLIENT_ID

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlops-inference
  namespace: mlops
  annotations:
    azure.workload.identity/client-id: INFERENCE_IDENTITY_CLIENT_ID

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow
  namespace: mlops
  annotations:
    azure.workload.identity/client-id: MLFLOW_IDENTITY_CLIENT_ID