apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlops-training
  namespace: mlops
  annotations:
    azure.workload.identity/client-id: AZURE_TRAINING_CLIENT_ID

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlops-inference
  namespace: mlops
  annotations:
    azure.workload.identity/client-id: AZURE_INFERENCE_CLIENT_ID

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow
  namespace: mlops
  annotations:
    azure.workload.identity/client-id: AZURE_MLFLOW_CLIENT_ID