apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlops-training
  namespace: mlops
  annotations:
    iam.gke.io/gcp-service-account: GCP_TRAINING_SERVICE_ACCOUNT

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlops-inference
  namespace: mlops
  annotations:
    iam.gke.io/gcp-service-account: GCP_INFERENCE_SERVICE_ACCOUNT

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow
  namespace: mlops
  annotations:
    iam.gke.io/gcp-service-account: GCP_MLFLOW_SERVICE_ACCOUNT