name: AWS Kubernetes - Build Model

on:
  workflow_dispatch:
    inputs:
      model_version:
        description: "Model version"
        required: true
        default: "v1"

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      MODEL_VERSION: ${{ inputs.model_version }}

      EKS_CLUSTER_NAME: mlops-thesis-k8s
      TRAIN_ECR_REPOSITORY: mlops-thesis-k8s-train

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Refresh EKS kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region "${AWS_REGION}" \
            --name "${EKS_CLUSTER_NAME}" \
            --alias "${EKS_CLUSTER_NAME}"

          kubectl config use-context "${EKS_CLUSTER_NAME}"


      - name: Check AWS identity
        run: |
          echo "AWS identity:"
          aws sts get-caller-identity

      - name: Check EKS cluster
        run: |
          echo "EKS cluster:"
          aws eks describe-cluster \
            --name "${EKS_CLUSTER_NAME}" \
            --region "${AWS_REGION}" \
            --query 'cluster.{name:name,status:status,version:version,authentication:accessConfig.authenticationMode}'

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2


      - name: Check ECR repository
        run: |
          aws ecr describe-repositories \
            --repository-names "${TRAIN_ECR_REPOSITORY}" \
            --region "${AWS_REGION}"


      - name: Build training image
        env:
          ECR_REGISTRY: 154959838069.dkr.ecr.us-east-1.amazonaws.com
        run: |
          docker build \
            -f docker/train/Dockerfile \
            -t "${ECR_REGISTRY}/${TRAIN_ECR_REPOSITORY}:${MODEL_VERSION}" \
            .


      - name: Push training image
        env:
          ECR_REGISTRY: 154959838069.dkr.ecr.us-east-1.amazonaws.com
        run: |
          docker push \
            "${ECR_REGISTRY}/${TRAIN_ECR_REPOSITORY}:${MODEL_VERSION}"


      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region "${AWS_REGION}" \
            --name "${EKS_CLUSTER_NAME}"


      - name: Check Kubernetes access
        run: |
          echo "Current Kubernetes context:"
          kubectl config current-context

          echo ""
          echo "Cluster info:"
          kubectl cluster-info

          echo ""
          echo "Nodes:"
          kubectl get nodes -o wide


      - name: Apply namespace
        run: |
          kubectl apply \
            -f kubernetes/namespace.yaml


      - name: Apply AWS ServiceAccounts
        run: |
          kubectl apply \
            -f kubernetes/aws-service-accounts.yaml

      - name: Check ServiceAccounts
        run: |
          kubectl get serviceaccounts \
            -n mlops

      - name: Prepare training Job
        env:
          ECR_REGISTRY: 154959838069.dkr.ecr.us-east-1.amazonaws.com
        run: |
          sed \
            -e "s|IMAGE_PLACEHOLDER|${ECR_REGISTRY}/${TRAIN_ECR_REPOSITORY}:${MODEL_VERSION}|g" \
            -e "s|MODEL_VERSION_PLACEHOLDER|${MODEL_VERSION}|g" \
            kubernetes/training/job.yaml \
            > /tmp/training-job.yaml

      - name: Start training Job
        run: |
          kubectl delete job mlops-training \
            -n mlops \
            --ignore-not-found

          kubectl apply \
            -f /tmp/training-job.yaml


      - name: Check training status
        run: |
          echo "Jobs:"
          kubectl get jobs -n mlops

          echo ""
          echo "Pods:"
          kubectl get pods -n mlops -o wide


      - name: Wait for training Job
        run: |
          kubectl wait \
            --for=condition=complete \
            job/mlops-training \
            -n mlops \
            --timeout=30m



      - name: Show training logs
        run: |
          kubectl logs \
            -n mlops \
            job/mlops-training