name: AWS Kubernetes - Build Model

on:
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    env:
      MODEL_BUCKET: mlops-thesis-k8s-xxxxx

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: pip install -r kubernetes/inference-requirements.txt

      - run: python ml/kubernetes/deploy.py